name: Markdown Syntax Validation
on: push

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.0.2

      - name: Download .markdownlint.json
        uses: wei/curl@master
        with:
          args: https://raw.githubusercontent.com/fharper/gh-configs/main/.markdownlint.json

      - name: Validate Markdown
        uses: DavidAnson/markdownlint-cli2-action@v7
        with:
            command: config
            globs: |
              .markdownlint.json
              **/*.md
              #**/node_modules
